@BASE_URL={{baseUrl}}
@BASE_URL_FOR_TODO={{BASE_URL}}/todos

###
POST {{BASE_URL_FOR_TODO}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "New Todo"
}

###
GET {{BASE_URL_FOR_TODO}}
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}?page=2&size=30
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}?searchTerm=Todo's Title 1
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}?completed=true
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}?completed=false
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}?page=1&size=2&searchTerm=title 3&completed=false
Authorization: Bearer {{accessToken}}

###
GET {{BASE_URL_FOR_TODO}}/1
Authorization: Bearer {{accessToken}}

###
PATCH {{BASE_URL_FOR_TODO}}/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "New Title"
}

###
PATCH {{BASE_URL_FOR_TODO}}/1/complete
Authorization: Bearer {{accessToken}}

###
PATCH {{BASE_URL_FOR_TODO}}/1/uncomplete
Authorization: Bearer {{accessToken}}

###
DELETE {{BASE_URL_FOR_TODO}}/1
Authorization: Bearer {{accessToken}}