@BASE_URL={{baseUrl}}
@BASE_URL_FOR_USER={{BASE_URL}}/users

###
GET {{BASE_URL_FOR_USER}}

###
GET {{BASE_URL_FOR_USER}}?size=7&page=3

###
GET {{BASE_URL_FOR_USER}}?name=Name 3

###
GET {{BASE_URL_FOR_USER}}?name=Name 3&size=2&page=3

###
GET {{BASE_URL_FOR_USER}}/1

###
PATCH {{BASE_URL_FOR_USER}}/1
Content-Type: application/json

{
    "fullname": "Johnny Doe"
}


###
DELETE {{BASE_URL_FOR_USER}}/1